//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Otomasyon_Projesi_YZM3101
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBOtelEntities : DbContext
    {
        public DBOtelEntities()
            : base("name=DBOtelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblIptalEdilenRezervasyonlar> tblIptalEdilenRezervasyonlar { get; set; }
        public virtual DbSet<tblKrediKartlari> tblKrediKartlari { get; set; }
        public virtual DbSet<tblKullanicilar> tblKullanicilar { get; set; }
        public virtual DbSet<tblKullaniciTipleri> tblKullaniciTipleri { get; set; }
        public virtual DbSet<tblMusteriler> tblMusteriler { get; set; }
        public virtual DbSet<tblOdaDurum> tblOdaDurum { get; set; }
        public virtual DbSet<tblOdalar> tblOdalar { get; set; }
        public virtual DbSet<tblOdaTipleri> tblOdaTipleri { get; set; }
        public virtual DbSet<tblRezervasyon> tblRezervasyon { get; set; }
        public virtual DbSet<tblRezervasyonDurum> tblRezervasyonDurum { get; set; }
        public virtual DbSet<tblRezervasyonTipleri> tblRezervasyonTipleri { get; set; }
        public virtual DbSet<tblTabanFiyatlar> tblTabanFiyatlar { get; set; }
    }
}
