//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Otomasyon_Projesi_YZM3101
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKrediKartlari
    {
        public int krediKartiID { get; set; }
        public long kartNumarasi { get; set; }
        public string kartUzerindekiAd { get; set; }
        public System.DateTime sonKullanımTarihi { get; set; }
        public string guvenlikKodu { get; set; }
    }
}
