//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Otomasyon_Projesi_YZM3101.ModelKatmani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblIptalEdilenRezervasyonlar> tblIptalEdilenRezervasyonlar { get; set; }
        public DbSet<tblKrediKartlari> tblKrediKartlari { get; set; }
        public DbSet<tblKullanicilar> tblKullanicilar { get; set; }
        public DbSet<tblKullaniciTipleri> tblKullaniciTipleri { get; set; }
        public DbSet<tblMusteriler> tblMusteriler { get; set; }
        public DbSet<tblOdaDurum> tblOdaDurum { get; set; }
        public DbSet<tblOdalar> tblOdalar { get; set; }
        public DbSet<tblOdaTipleri> tblOdaTipleri { get; set; }
        public DbSet<tblRezervasyon> tblRezervasyon { get; set; }
        public DbSet<tblRezervasyonDurum> tblRezervasyonDurum { get; set; }
        public DbSet<tblRezervasyonTipleri> tblRezervasyonTipleri { get; set; }
        public DbSet<tblTabanFiyatlar> tblTabanFiyatlar { get; set; }
    }
}
