//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Otomasyon_Projesi_YZM3101.ModelKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRezervasyonDurum
    {
        public int rezervasyonDurumID { get; set; }
        public string durumAciklama { get; set; }
    }
}
