//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Otomasyon_Projesi_YZM3101.ModelKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRezervasyon
    {
        public int rezervasyonID { get; set; }
        public Nullable<int> OdaID { get; set; }
        public System.DateTime baslangicTarihi { get; set; }
        public System.DateTime bitisTarihi { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public int rezervasyonTipID { get; set; }
        public int rezervasyonDurumID { get; set; }
        public int tabanFiyatID { get; set; }
        public System.DateTime rezervasyonOlusturmaTarihi { get; set; }
        public int musteriID { get; set; }
        public string Yorum { get; set; }
    }
}
